version: "3.6"

services:
  db:
    image: catalogqt/db
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=1

  server:
    image: catalogqt/server
    depends_on:
      - db

  updateprocess:
    image: catalogqt/updateprocess
    depends_on:
      - server

  watchdog:
    image: catalogqt/watchdog
    depends_on:
      - server

  react:
    image: registry.apps.man.poznan.pl/f4f/dashboard-ui/assets:branch-develop
    environment:
      - LISTEN_PORT=9100
      - S6_READ_ONLY_ROOT=1

  nginx:
    image: nginx
    volumes:
      - ./volumes/nginx/reverse-proxy.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
    depends_on:
      - react
