version: "3.6"

services:
  db:
    image: catalogqt/db
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=1

  server:
    image: catalogqt/server
    ports:
      - 8080:8080
    volumes:
      - imasdb:/home/imas/public/imasdb

  updateprocess:
    image: catalogqt/updateprocess
    volumes:
      - imasdb:/home/imas/public/imasdb

  inotify:
    image: catalogqt/inotify
    volumes:
      - imasdb:/home/imas/public/imasdb
      - ./fair4fusion-docker-demo:/docker-entrypoint-properties.d
